swagger: "2.0"
info:
  version: "0.0.1"
  title: SF Contacts API
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
schemes:
  # tip: remove http to make production-grade
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /contacts:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns contacts that the user has access to
      # used as the method name of the controller
      operationId: GetAllContacts
      parameters:
        - name: start
          in: query
          description: The page number to start on for paginated contacts.
          required: false
          type: integer
        - name: limit
          in: query
          description: The maximum number of contacts to retrieve.
          required: false
          type: integer
        - name: search
          in: query
          description: Will return only contacts containing this string.
          required: false
          type: string
        - name: orderBy
          in: query
          description: Field to order the contacts by
          required: false
          type: string
        - name: orderDesc
          in: query
          description: Sort contacts descending (ascending is default)
          required: false
          type: boolean  
      responses:
        "200":
          description: An array of contacts
          schema:
            type: array
            items:
              $ref: "#/definitions/Contact"
            # a pointer to a definition
            # $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      summary: Create a contact
      description: Add a new Todo for a user
      operationId: CreateContact
      parameters:
      - in: body
        name: contact
        description: The contact to be created
        required: true
        schema:
          $ref: "#/definitions/Contact"
      responses:
        200:
          description: Successfully created contact
          schema:
            type: integer
            description: Id of the newly created contact
  /contacts/{id}:
    get:
      summary: Retrieves a single contact
      description: Gets the information for a contact by id
      parameters:
      - name: id
        in: path
        description: Id of the contact to get
        required: true
        type: integer
      responses:
        200:
          description: Retrieved contact
          schema:
            $ref: "#/definitions/Contact"
    
    put:
      summary: Updates a single contact
      description: Edits the information for a contact by id
      parameters:
      - name: id
        in: path
        description: Id of the contact to update
        required: true
        type: integer
      - name: contact
        in: body
        description: The contact to be updated
        required: true
        schema:
          $ref: "#/definitions/Contact"
      responses:
        200:
          description: Updated contact
          schema:
            $ref: "#/definitions/Contact"
            
    delete:
      summary: Deletes a contact
      description: Deletes the information for a contact by id
      parameters:
      - name: id
        in: path
        description: Id of the contact to get
        required: true
        type: integer
      responses:
        204:
          description: Deleted contact
    
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  Contact:
    type: object
    properties:
      id:
        type: integer
        description: Id of the contact object
      pictureUrl:
        type: string
        description: Url for the contact's image
      firstName:
        type: string
        description: First name of the contact
      lastName:
        type: string
        description: Last Name of the contact
      dateOfBirth:
        type: string
        format: date
        description: Date of birth of the contact
      phoneNumber:
        type: integer
        description: Phone number of the contact. Numbers only.
      zipCode:
        type: string
        description: Zip code of the contact. Contains numbers and up to one hyphen character
      starred:
        type: boolean
        description: Is the contact starred
      note:
        type: string
        description: User added note about the contact
      dateAdded:
        type: string
        format: data-time
        description: Timestamp of when the contact was create. Set by the server
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
